### PR TITLE
[OMP] #5833 seriesPosition goes to publication_settings table instead of publications table

### PR DESCRIPTION
**Pull request by defstat**

### CODE REVIEW

**Comment by asmecher** [comment]
@defstat, is the data from previous versions still in `series_position`, or did it get moved into `publication_settings`? (If the latter, there will need to be an upgrade script to move it back.)

@NateWr, the `series_position` field is a weird one because it's both plain-text metadata (entered by the author, non-localized) and a sort-by option. I lean towards keeping it as a separate column, rather than a `publication_settings` entry, because sort performance on `publication_settings` will be very poor. But I'm not sure how that plays with your plans/design for the schema toolset.

**Comment by defstat** [comment]
@asmecher  
> is the data from previous versions still in series_position, or did it get moved into publication_settings? (If the latter, there will need to be an upgrade script to move it back.)

the 3.1.2 OMP version (and versions before that I assume) preserves the `series_possition` in `submisions` -> `series_possition` column

**Comment by NateWr** [comment]
Yeah, as far as I'm aware in OMP the `series_position` should be in the `publication` table, not `publication_settings`. This shouldn't cause any problems with the schema system because it manages data in the primary column as well. The obvious downside is that it can not be multilingual.

Perhaps an index should be added?

**Comment by defstat** [comment]
@NateWr @asmecher 

Also added an upgrade script change to fix possible seriesPosition entries in the publication_settings table (from 3.2.x to 3.2.1)

**Comment by asmecher** [comment]
Looks good -- thanks, @defstat. Please go ahead and merge when you're ready.

**Pull request merged**
