### PR TITLE
Syntax issue on string #46, plus some typo on #51

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by mtub** [comment]
@marcbria, any thoughs?

**Comment by asmecher** [comment]
@kant, some of the changes here were already committed into the `master` branch, but I adapted the rest manually. Thanks for contributing!

**Comment by marcbria** [comment]
Sorry. I missed this one till Alec made his comment.
Some of the changes ("email" to "correo electrónico") were not mandatory but it's fine.
Other changes were important so thanks for the commit.

**Comment by marcbria** [comment]
Sorry. I missed this one till Alec made his comment.
Some of the changes ("email" to "correo electrónico") were not mandatory but it's fine.
Other changes were important so ok with the merge.
Thanks for the commit @kant.

**Pull request closed without merging**
