### PR TITLE
pkp/pkp-lib#983 improve reviewer selection

### PR DESCRIPTION
**Pull request by NateWr**
See https://github.com/pkp/pkp-lib/issues/983 for comments.

### CODE REVIEW

**Comment by NateWr** [comment]
It's not clear to me why the test is failing. As far as I can tell, it should be able to pass `testCIDisabled` and I'm not sure how to further test and fix the error...

**Comment by asmecher** [comment]
The tests failed in different places, suggesting there was a server interruption. I've restarted both MySQL and PostgreSQL jobs and we'll see if it clears.

**Comment by asmecher** [comment]
Now both tests agree that the CI test is broken :) will investigate.

**Comment by asmecher** [comment]
Nate, this should fix it. Mind cherry-picking into your pull request?
https://github.com/asmecher/pkp-lib/commit/b4e003e9f63804ce5e30fd89ba393856560b8fb1

**Comment by NateWr** [comment]
Cherry-picked, tests running. Thanks.

**Comment by asmecher** [comment]
Hmm, looks like other tests are having trouble now. Will investigate.

**Comment by asmecher** [comment]
The problem appears to be the "days since last review" field -- it's not handling a NULL case (where no reviews have been completed) gracefully. Considering changing...

    MAX(raf.date_assigned) <= xxx AND MAX(raf.date_assigned) >= yyy

...to...

    COALESCE(MAX(raf.date_assigned), NOW()) <= xxx AND COALESCE(MAX(raf.date_assigned), NOW()) >= yyy

...but will think of a cleaner way.

**Comment by asmecher** [comment]
Hmm. @NateWr, we need to consider how two of the reviewer search form fields will behave for reviewers who have completed no reviews at all:
- Average days to complete
- Days since last review

I think as Editor if I wanted to work with these criteria I would not expect to see any reviewers who hadn't completed a review. But currently there's no way of disabling the criteria entirely.

**Comment by NateWr** [comment]
@asmecher I wondered about this when I was working on it. I thought about possibly getting rid of the min/max and using a single limiting value. Can we make the following assumptions about user intention?

- __Average days to complete:__ the editor wants to weed out reviewers who take too long.
- __Days since last review:__ the editor wants to find reviewers they haven't tapped too recently.

If that is generally the use-case for those filters, then I'd say we could change them to a single limiting value.

__Average days to complete less than:__ `[value]`
__Days since last review more than:__ `[value]`

That would allow us to interpret a `0` value as disabling the filter. I could replace the `0` value with an infinity symbol (`∞`) in the UI (though we'd still send `0` to the server).

It would require some work on the `rangeSlider` component and probably some functionality specific to these fields.

**Comment by asmecher** [comment]
One alternate assumption rather than "Average days to complete: the editor wants to weed out reviewers who take too long" might be "The editor wants someone who they can expect to be reliable". Including never-used reviewers wouldn't suit that need.

This is a situation where I'd be tempted to use a checkbox to enable/disable filter criteria, but won't be surprised if you don't like the idea, because it'll make controls tough to organize/label coherently. If that's the case, then I suppose custom work on those controls is probably inevitable.

**Comment by NateWr** [comment]
Ok, well I can't think of anything better. Maybe a checkbox that is inline with the label/value display?

**Comment by asmecher** [comment]
Yes, though accessibility might be a problem -- each control would have to have its own label.

**Comment by NateWr** [comment]
Merge conflicts. [New PR](https://github.com/pkp/omp/pull/200).

**Pull request closed without merging**
