### PR TITLE
pkp-lib#1483 backend style

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by asmecher** [comment]
Tests appeared to time-out; I've restarted and we'll see if that helps.

**Comment by NateWr** [comment]
Looks like the tests stalled again.

**Comment by asmecher** [comment]
Hmm, interesting. Will run them locally.

**Comment by asmecher** [comment]
Tests run locally. Cherry-picked into master, will see if something has jarred loose.

**Pull request closed without merging**
