### PR TITLE
Missing translation

### PR DESCRIPTION
**Pull request by FSaldanha**
submission.editorName was not being displayed in pt_BR

### CODE REVIEW

**Comment by asmecher** [comment]
(Tagging @mtub)

**Comment by Mandroide** [comment]
> (Tagging @mtub)

@asmecher This PR is not necessary anymore. It could be closed.

**Comment by asmecher** [comment]
@Mandroide, thanks for the heads-up -- and @FSaldanha, I'm sorry for letting this slip past so long ago! FYI, we have launched a new translation service that's much easier to use... https://translate.pkp.sfu.ca

**Comment by FSaldanha** [comment]
No problem, @asmecher! In fact, I'm already signed up to this new service :)

**Pull request closed without merging**
