### PR TITLE
pkp/pkp_lib#836 Homepage design

### PR DESCRIPTION
**Pull request by NateWr**
This is a replay of #161 after we had some submodule commit problems.

### CODE REVIEW

**Comment by asmecher** [comment]
Nate, the Travis testing is a little flaky lately, but did you see this? https://travis-ci.org/pkp/omp/jobs/91812025

**Comment by NateWr** [comment]
Ok i'll take a look at those. I'm stepping away for the evening now, so may not get to it until next week. But I'll try to take a peek tomorrow before our meeting if I can.

**Comment by asmecher** [comment]
I'll take care of it -- plenty of morning left over here, and I'd like to get everything squared away for tomorrow.

**Comment by NateWr** [comment]
Ok, it seemed pretty simple. Haven't tested but that should fix the tests. Do I need to re-order the Submodule update again?

**Comment by asmecher** [comment]
Don't worry -- I've already got your branch checked out over here & I'll cherry-pick in that push you just made.

**Comment by NateWr** [comment]
Thanks! Talk to you tomorrow at the meeting.

**Comment by asmecher** [comment]
Replaced by https://github.com/pkp/omp/pull/164

**Pull request closed without merging**
