### PR TITLE
pkp/pkp-lib#1694 Move chapterId to SubmissionFile

### PR DESCRIPTION
**Pull request by bozana**
S. https://github.com/pkp/pkp-lib/issues/1694

### CODE REVIEW

**Comment by bozana** [comment]
hmmm... a test failed, but locally all were went through... hmmm...

**Comment by asmecher** [comment]
99% sure that's some kind of race condition; I've restarted the job and we'll see if it goes through.

**Comment by bozana** [comment]
ok, thanks!!!

**Comment by bozana** [comment]
Juhuuuuuu the test passed... :-)

**Pull request merged**
