### PR TITLE
pkp/pkp-lib#1470 fix cover image access

### PR DESCRIPTION
**Pull request by bozana**
S. https://github.com/pkp/pkp-lib/issues/1470

### CODE REVIEW

**Comment by asmecher** [comment]
Was this also broken in 1.2.0?

**Comment by bozana** [comment]
Hmmm... maybe... Now when I search fir it I believe this function is not used anymore... only thumbnail...

**Comment by bozana** [comment]
Hmmm.... shall I then remove or leave it?

**Comment by bozana** [comment]
I tested it so: I clicked to view a book image in the browser and then changed the "thumbnail" in the URL with "cover"...

**Comment by asmecher** [comment]
@NateWr, I think you tinkered with this when you worked on the OMP front-end -- is that legitimately dead code?

**Comment by NateWr** [comment]
If you're asking if the frontend uses the full-size cover image at any point, it does not. I suspect that we may want to use it at some point, though, either in the default theme or an alternate theme.

**Comment by bozana** [comment]
I would then recommend to keep the function for later. And to keep it in the master branch only. And to close this issue. OK? /* Hihihihi, I think I got Alec's 'flu' of trying to decrease the issue numbers :-DDD */

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
I've got the flu, and you'd better catch it too :)

**Comment by bozana** [comment]
Rhyming Rabbit :-)

**Comment by asmecher** [comment]
Also cherry-picked over to `omp-stable-1_2_0` and `omp-dev-1_2`.

**Pull request merged**
