### PR TITLE
Remove no action message grid logic

### PR DESCRIPTION
**Pull request by NateWr**
[pkp-lib PR](https://github.com/pkp/pkp-lib/pull/962)

### CODE REVIEW

**Comment by beghelli** [comment]
@NateWr I believe you will solve the visual problem that was the cause to introduce this no message logic after right?

**Comment by NateWr** [comment]
@beghelli What's the visual problem? I believe it was only ever used in the approvals grid, and since Alec has rebuilt that I don't think it's ever actually used...

**Comment by beghelli** [comment]
@NateWr read this comment: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=7951#c4

Generally, I think that's not a crucial issue. That can also happen (I think it already happens) in the plugin's grid, where some plugin rows have actions and others don't. But as I said, I don't think that's a priority now.

**Comment by beghelli** [comment]
@NateWr Actually it doesn't happen on the plugin's grid, sorry about that. Anyway, I think the clean up is correct, and when we have that problem (if we have) we can solve when it arises.

**Comment by NateWr** [comment]
Yeah, my understanding is that a grid has to explicitly add support for it, like the approvals grid [used to](https://github.com/pkp/omp/pull/177/files#diff-99b0aca3c62e5285645bb240a8ea0d3cL64). That's the only grid I was able to find like that (searched for `NoActionMessage`).

**Pull request merged**
