### PR TITLE
pkp/pkp-lib#932 Improve grid dropdowns

### PR DESCRIPTION
**Pull request by NateWr**
Still couldn't quite get the Travis CI to kick in after squashing the commits, so here's a new PR instead.

### CODE REVIEW

**Comment by asmecher** [comment]
The submodule commit not appearing last in the list might cause problems.

**Comment by NateWr** [comment]
Err... it's [there](https://github.com/NateWr/omp/commits/i932_improve_grid_dropdowns), so where'd it go?

**Comment by NateWr** [comment]
Ugh, it looks like the `pkp-lib` stuff has merge conflicts anyway. I'll just create a new branch and cherry-pick everything in and issue a new PR. Sorry for all the noise.

**Comment by asmecher** [comment]
And this is partially my doing because I keep committing new stuff to master. I'm out for the afternoon -- let me know how far you get and I can pick it up from there.

**Pull request closed without merging**
