### PR TITLE
pkp/pkp-lib#1931 signoffs migration fix

### PR DESCRIPTION
**Pull request by bozana**
s. https://github.com/pkp/pkp-lib/issues/1931

### CODE REVIEW

**Comment by bozana** [comment]
@asmecher, any idea why these tests are failing?

**Comment by asmecher** [comment]
@bozana, try rebasing on top of the latest `pkp-lib`. There was [an accidental add](https://github.com/pkp/pkp-lib/commit/5dec016d78ae7634ad86725cc93ebe384e5482a9) that caused `lib/pkp` to fail checkouts; it's already been fixed.

**Comment by bozana** [comment]
@asmecher, but this is only omp change, thus those lib-pkp branches might all have that accidental add i.e. this might be removed from every branch?

**Comment by asmecher** [comment]
Sorry, I'm still catching up on old emails. It looks like you've already fixed the accidental add that made it into other branches, thanks! I had assumed that it only went into the master branch.

**Pull request merged**
