### PR TITLE
Update skipLinks.tpl

### PR DESCRIPTION
**Pull request by ajnyga**

### CODE REVIEW

**Comment by ajnyga** [comment]
@asmecher this is just a typo correction, one test failed probably with no particular reason.

**Comment by asmecher** [comment]
@ajnyga, I've restarted the test and expect it'll pass.

**Comment by ajnyga** [comment]
the tests passed

**Comment by ajnyga** [comment]
@asmecher this is also ready for merging and tests passed.

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
