### PR TITLE
pkp/pkp-lib#925 Add margins and clear floats in file downloads on fro…

### PR DESCRIPTION
**Pull request by NateWr**
…ntend

### CODE REVIEW

**Comment by NateWr** [comment]
Oh, hold off on merging this. I didn't notice there's more to the ticket. I'll try to bang that out real quick.

**Comment by NateWr** [comment]
Never mind, go ahead and merge this. THe other part of the ticket relates to DOIs and I'll need to spend some time figuring all that out.

**Comment by NateWr** [comment]
Not sure what happened with Travis here, but these are just CSS adjustments so shouldn't effect the tests in any way.

**Comment by asmecher** [comment]
Nate, something I merged yesterday broke tests involving listbuilders and a "wait for JQuery" Selenium operation. I'll look into it further after the call.

**Pull request merged**
