### PR TITLE
pkp/pkp-lib#4901 Missing translation key

### PR DESCRIPTION
**Pull request by tgc**
Key was renamed in #4446.

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @tgc, this looks great! I noticed that we still have several locales with the `catalog.noTitlesSection` string. Can you find and remove those and add that commit to this PR? That way the translators will know they need to retranslate this string.

**Comment by tgc** [comment]
I don't see how they can be part of this PR as they are in their own repo (pkp-lib).

**Comment by tgc** [comment]
See: https://github.com/pkp/pkp-lib/pull/4911

**Comment by NateWr** [comment]
That's great, thanks @tgc! Looks like the mysql tests failed, but that is likely just a race condition. I've restarted them and I'm happy to merge this once they've passed.

**Pull request merged**
