### PR TITLE
pkp/pkp-lib#836 Remove featured books from category and series pages

### PR DESCRIPTION
**Pull request by NateWr**
They'll go on the homepage now.

### CODE REVIEW

**Comment by asmecher** [comment]
OTOH the back-end "feature" interface still supports creating features in these different contexts, though, doesn't it?

**Comment by NateWr** [comment]
Does it? The `diff` you sent to try and get features working includes only two links for me. Neither works so I don't know if they are meant to pop up modals or anything. I thought they were just global toggles.

featured-items

**Comment by asmecher** [comment]
It depends [or used to, when it was working] what part of Catalog Management you were working with. If you were working on a specific series, then the Feature was applied to that series. If you were on the homepage tab, then you were setting the features for the homepage. And so on -- not to suggest that we should keep it if that level of detail is not useful, but that's what it was originally designed to do.

**Comment by NateWr** [comment]
Am I supposed to be able to view and edit monograph entries in the category and series sections here?

category-management

**Comment by asmecher** [comment]
Yes, choosing a category using the drop-down should bring up a list of submissions in that category. Likewise for series etc.

**Comment by NateWr** [comment]
Ok, maybe this is still part of my borked database charset. I should really fix that.

**Pull request closed without merging**
