### PR TITLE
pkp/pkp-lib#685 data privacy for OMP usage stats plugin

### PR DESCRIPTION
**Pull request by bozana**
I would like to make the pull request for this branch, if someone would like to use it immediatelly...
I will then port it to master too, although the master branch seems to currently be in havy development...

### CODE REVIEW

**Comment by bozana** [comment]
could you cherry-pick the first commit to the master or shall I make a new pull request?

**Comment by bozana** [comment]
There was a change in pkp-lib. Should I remove the last 'submodule update' commit and add the new one, or could I only add the new one without removing the old one?

**Comment by asmecher** [comment]
The checkout script in the Travis testing will get confused if there's more than one submodule update, or if it's not the last commit. What I do is...

    git add lib/pkp
    git commit -m "Second commit to be merged into the last one"
    git rebase -i official/[branch I originally forked from]

Then use the editor to change the "pick" beside "Second commit..." into a "fixup". It'll combine that commit with the one immediately above it.

Note that this requires a force-push to your github.com branch, so it should only be done with personal branches, not something that another person is working with.

**Comment by bozana** [comment]
Thaks @asmecher I will do so :-)

**Comment by bozana** [comment]
OK, done, is this now OK?

**Comment by beghelli** [comment]
Yes Bozana, it seems that way. Waiting for the test to complete and will merge. After that I will apply the download log fix. Thanks.

**Comment by bozana** [comment]
I already applied the fix (that's why the submodule hash changed ;-)) s. https://github.com/bozana/pkp-lib/commit/2d30c45eff653114612fd9d376ccea2f665569c9

**Comment by asmecher** [comment]
(@beghelli and @bozana, as I just noted on another one -- could you make sure there's something to track the forward-porting work?)

**Pull request merged**
