### PR TITLE
Semantic issues on #49 & #72

### PR DESCRIPTION
**Pull request by kant**
#72: `compromiso por su parte` --> `compromiso de su parte`

### CODE REVIEW

**Comment by mtub** [comment]
@marcbria, could you have a look?

**Comment by marcbria** [comment]
I'm unsure about this and our translator is on vacations till 1st September.
I think @kant is right, so if we are in a hurry, accept the PR.

**Comment by mtub** [comment]
Any update, @marcbria ?

**Comment by marcbria** [comment]
Both expressions are right, but in Spanish from Spain, the most common is "compromiso por su parte" so it don't need to be fixed: https://github.com/pkp/omp/pull/72

"contactarse" is wrong in EU spanish (need to be "contactar"), although I know is a common form in south america.

The rest of proposed changes don't fix any error... are just style preferences, so I suggest don't make any change in this file.

Any way thanks a lot to @kant for the proposal.

**Pull request closed without merging**
