### PR TITLE
pkp/pkp-lib#6057 Refactor submission files

### PR DESCRIPTION
**Pull request by NateWr**
Here's the OMP pull request. There's a fair bit of new work to look at here because of the additional considerations for publication formats, chapter files, pub ids and payments.

### CODE REVIEW

**Comment by NateWr** [comment]
@asmecher I forgot to ask if you had time to help out with the following:

- There's a lot going on with the `SubmissionFileDAOTest`. I'm not too familiar with the PHPUnit tests. Would you be able to look over that and make the necessary adjustments? Or give me some pointers?
- `Upgrade::fixFilenames()` uses `glob()`.  I'm not sure how to handle this with flysystem. Do you have any ideas here?
- `OMPPaymentManager::createQueuedPayment()` adds a request url which is eventually passed as a "backlink" in the manual payment workflow. I tried to fix it, but I'm not sure what it is supposed to do. It looks like it is meant to send the user back to the submission file, but that won't work because access to the submission file is blocked... it just puts the user into a loop. Any ideas here?

**Comment by NateWr** [comment]
@asmecher I don't actually see `SubmissionFileDAOTest` being run in the test log. Is it used? https://travis-ci.org/github/pkp/omp/jobs/739626662

**Comment by asmecher** [comment]
> I don't actually see SubmissionFileDAOTest being run in the test log. Is it used?
Yes -- it's in the PHPUnit output, which just shows a `.` for each test executed unless you add `--debug` to the command line:
```
$ php lib/pkp/lib/vendor/phpunit/phpunit/phpunit --configuration /home/asmecher/git/omp/lib/pkp/tests/phpunit-env1.xml -v tests/classes --debug
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3
Configuration: /home/asmecher/git/omp/lib/pkp/tests/phpunit-env1.xml

Test 'SubmissionFileDAOTest::testSubmissionFileCrud' started
Test 'SubmissionFileDAOTest::testSubmissionFileCrud' ended
Test 'SubmissionFileDAOTest::testNewDataObjectByGenreId' started
Test 'SubmissionFileDAOTest::testNewDataObjectByGenreId' ended


Time: 520 ms, Memory: 14.00 MB

OK (2 tests, 125 assertions)
```

**Review by asmecher — APPROVED** [review]
Looks good, Nate -- but will definitely need some testing!

**Comment by NateWr** [comment]
I think I've adequately addressed the `SubmissionFileDAOTest`. It is much reduced because there is no up/down casting of `SubmissionFile` object classes and the revision structure is simpler. But I think I've tested the primary concerns with the tests: https://github.com/pkp/omp/pull/871/commits/7900698d769eecea13e8ea39e743feef20bf0fe2

**Comment by asmecher** [comment]
Great, and I'll take a look over the simplified code for some areas of clean-up that the upcast/downcast removal permits -- there should be some infrastructural complexity that's no longer used as a result.

**Pull request merged**
