### PR TITLE
pkp/pkp-lib#836 Prevent dropdown menus from opening off-screen

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by asmecher** [comment]
You're missing the last two `##` at the end of the submodule commit message, so the Travis tests didn't work.

**Comment by NateWr** [comment]
Fixed.

**Comment by NateWr** [comment]
Hmm, I added a new commit to fix another issue with the nav menus. I then re-ordered the commits in the history so that the submodule commit is last. It appears in the "correct" order in [my branch](https://github.com/NateWr/omp/commits/i836_fix_offscreen_menu_dropdowns), but is listed by the time when the commit was made here....

**Comment by asmecher** [comment]
You probably have to do a force-push, I think.

**Comment by NateWr** [comment]
Yeah I did do a force-push, which is why the order is correct in my branch. It just doesn't seem to have picked that up here...

**Comment by asmecher** [comment]
I'll cherry-pick this stuff into master. You've got enough git/travis wrestling on your hands without it :)

**Comment by NateWr** [comment]
Thanks! :+1:

**Comment by asmecher** [comment]
Cherry-picked.

**Pull request closed without merging**
