### PR TITLE
Add Google Scholar support for chapters

### PR DESCRIPTION
**Pull request by withanage**
#### Description

- Add Google Scholar Support for chapters

#### Issue
https://github.com/pkp/pkp-lib/issues/7003

### CODE REVIEW

**Comment by asmecher** [comment]
@withanage, I don't see where `isChapterRequest` is being set... Is that somewhere else?

**Comment by withanage** [comment]
> @withanage, I don't see where `isChapterRequest` is being set... Is that somewhere else?

@asmecher  this  seems to have been set in the CatalogBookHandler and is accessible for the plugin.

https://github.com/pkp/omp/blob/main/pages/catalog/CatalogBookHandler.inc.php#L151

**Comment by asmecher** [comment]
@withanage, [this test failure](https://app.travis-ci.com/github/pkp/omp/builds/246669977) should be corrected with a pkp-lib update.

**Comment by withanage** [comment]
Thanks @asmecher  !
Have updated the submodule and the tests are passing.

**Comment by asmecher** [comment]
Thanks, @withanage, I've merged it!

**Pull request merged**
