### PR TITLE
pkp/pkp-lib#3578: cleaning up FileManager signatures

### PR DESCRIPTION
**Pull request by crism**
Addresses part of pkp/pkp-lib#3578 as discussed on Slack. Will break some plugins.

### CODE REVIEW

**Comment by asmecher** [comment]
The checks on this one failed, @crism.

**Comment by crism** [comment]
@asmecher, see [this comment](https://github.com/pkp/ojs/pull/2032#issuecomment-404875195).

**Comment by crism** [comment]
The checks here seem to be failing on module resolution in NPM… no idea why my changes would affect that:
```
ERROR in multi babel-polyfill ./lib/ui-library/src/styles/_global.less ./js/load.js
Module not found: Error: Can't resolve './lib/ui-library/src/styles/_global.less' in '/home/travis/build/pkp/omp'
 @ multi babel-polyfill ./lib/ui-library/src/styles/_global.less ./js/load.js
```

**Comment by crism** [comment]
@asmecher, I squashed the `pkp-lib` dependency commits… this is now failing on `assertTextPresent('OMP Installation')`. That sounds like a general systems failure… not sure how to get the screenshots off of Travis, though, to see what’s going on.

**Comment by crism** [comment]
`UsageStatsLoader` imports `PKPUsageStatsLoader`, which no longer exists in `pkp-lib`. What happened here?

**Comment by crism** [comment]
Can confirm that eliminating `UsageStatsLoader` allows OMP to load… will file separate issue on that.

**Comment by asmecher** [comment]
Cherry-picked manually (https://travis-ci.org/pkp/omp/builds/408271702).

**Pull request closed without merging**
